### ISSUE TITLE
Does this work with Beast?

### ISSUE THREAD

**Issue by vinniefalco** [inetic/asio-utp#2]
I'd like to know if Beast's HTTP stream algorithms work with asio-utp:
https://github.com/boostorg/beast/

**Comment by inetic** [comment]
That is the goal :)

I have just tested to modify your http coro client but unfortunately it's not yet there. I fixed the [first issue](https://github.com/inetic/asio-utp/commit/994f50f1d56d0f12ab97cc75f73f305ddd66fadf) but now I hit the problem that Beast's handlers aren't copyable (I'm storing them in `std::function` and that requires it).

I'm trying some workarounds

**Comment by vinniefalco** [comment]
Hmm... putting handlers in `std::function<void>` is a very bad idea, it will cause strands to break and will often lead to undefined behavior / crashes. In general you cannot type-erase a completion handler.

**Comment by inetic** [comment]
Yeah, I've been told in [the other issue](https://github.com/inetic/asio-utp/issues/1) about the strand and custom allocator breaking. I have some ideas on how to deal with it.

But apart from that I'm not sure I understand why moving a handler with `void operator()(const error_code&, size_t)` into `std::function<void(const error_code&, size_t)>` should be problematic. I've done it in the past in a code without strands and without custom allocators without issues. It's entirely possible I'm missing something though.

I've been playing with the code since my above comment and it's not only the `std::function` that needs the handler to be copy-able. The [`executor::post`](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/executor/post.html) function (which I need to use internally) also needs to create handler copies. 

My current workaround for the Beast test is going to move the handlers into `std::shared_ptr<std::function<void(const error_code&, size_t)>>` that should tick all the boxes for now.

I'm not too happy about that solution as it will involve two allocations, but I have some ideas about how to fix that as well.

Whatever approach I'll end up using, I think I won't be able to do 100% without type erasures as I need to store the handlers somewhere and wait until `libutp` tells me I can execute them (e.g. when data is received).

**Comment by vinniefalco** [comment]
> I'm not sure I understand why moving a handler...should be problematic

Consider the following completion handler:
```
struct my_handler
{
  struct executor_type; // defined later
  executor_type get_executor() const noexcept; // defined later
  void operator()(error_code, std::size_t);
};
```

Given an object of this type:
```
my_handler h;
```

The expression `boost::asio::get_associated_executor(h)` will return an object of type `my_handler::executor_type`.

On the other hand, given the following object:
```
std::function<void(error_code, size_t)> fh(my_handler{});
```

The expression `boost::asio::get_associated_executor(fh)` will return an object of type `boost::asio::system_executor`.

This of course is "very bad". Does this help?

**Comment by vinniefalco** [comment]
> Whatever approach I'll end up using, I think I won't be able to do 100% without type erasures

Yes, you are right about that, and the obvious place for a type erasure is when you give UTP the "userdata" for the callback, it can be a pointer to an abstract base class whose derived portion holds the original user-provided handler as a data member. You'll have to go through a virtual function call, which is not really a big deal.

The problem is that you have put the type-erasure at too low a level, it is erased before there is even a chance to do anything with it!

We can help you fix this a bit at a time if you are willing - it will be work, but you'll get a nice result.

**Comment by inetic** [comment]
> Consider the following completion handler: ... Does this help?

Right, that's why I said "apart from that [strand and allocator breaking]". I do understand the issue with custom executors and allocators inside `CompletionTokens` (although it really clicked only yesterday in [that reddit post](https://www.reddit.com/r/cpp/comments/abm21g/boostasio_wrapper_over_the_utorrents_utp_library/)  linked from [that other issue](https://github.com/inetic/asio-utp/issues/1) :-/).

**Comment by inetic** [comment]
> Yes, you are right about that, and the obvious place for a type erasure is when you give UTP the "userdata" for the callback, 

Unfortunately that won't work, with the `libutp` library one doesn't specify "userdata" per async action (e.g. [`async_write`](https://github.com/inetic/libutp/blob/6c9ee29ed1d3fd06ba1856f01c8dd88eccaca2fa/utp.h#L169)). One specifies userdata ["per-socket"](https://github.com/inetic/libutp/blob/6c9ee29ed1d3fd06ba1856f01c8dd88eccaca2fa/utp.h#L164). That is why I store the handlers in `socket_impl` class and userdata point to that.

**Comment by vinniefalco** [comment]
> that reddit post

Oh, heh, not sure I missed that! Yes I see.

> One specifies userdata "per-socket"

Well, yes you should put the handler in the `socket_impl` class and you will have to type-erase it. But `std::function` is not the way to do it. Here's an example of a type-erasing wrapper I use in Beast, it "parks" the handler so it can run later:

https://github.com/boostorg/beast/blob/8b72b4d407674176187f7427bd1e6a7c88192119/include/boost/beast/websocket/detail/saved_handler.hpp#L30

When this saved handler is invoked, it will very often be called from a foreign thread or strand. The first thing these saved operations do is use `post` to get back on the strand. You can do something similar in your type-erasing wrapper: store the handler, a work guard, and a copy of the I/O context's executor in the type-erased wrapper, and when the wrapper is invoked use `post` to invoke the handler on the correct executor.

**Comment by inetic** [comment]
(did not mean to close the issue, pressed the wrong button :-P)

**Comment by inetic** [comment]
>  it can be a pointer to an abstract base class whose derived portion holds the original user-provided handler as a data member. You'll have to go through a virtual function call, which is not really a big deal.

I did something similar [here](https://github.com/equalitie/ouinet/blob/master/src/generic_stream.h) (btw, that does work with beast :) ). I heard that `std::function` doesn't actually use vtable and I wanted to try to avoid it as well (though I agree with you that it's not _that_ big of a deal) so I started to write [this](https://github.com/inetic/asio-utp/commit/2070e447d9867264961b7a502bd2f0927d5a8163#diff-a102a4a7368da10ef115a389422c6388R16), but before I finished it I realized it won't fix the more imminent non-copyability issue (needed for `post`), so I kinda postponed it in favor of that `shared_ptr<function<...>>` solution.

Note that I do understand that neither of the two classes I mention in the above paragraph solve the `executor` problem, my intention was to put the non-vtable approach on the table.

> We can help you fix this a bit at a time if you are willing - it will be work, but you'll get a nice result.

I'd be very happy to :)

**Comment by vinniefalco** [comment]
If you could give a description of how utp works, and how you have integrated it (for example, that there is only one "userdata" for the whole UTP socket instead of per-operation) that would be great

**Comment by vinniefalco** [comment]
> I did something similar here

Wooh that is some heavy type erasing! I think it would be more appropriately named `any_stream`.

There is really no reason to avoid a virtual function call, if you are worried about the cost, don't be - it is insignificant compared to the cost of I/O.

**Comment by inetic** [comment]
> I think it would be more appropriately named any_stream.

Sounds good, but is there a convention I should know about?

> There is really no reason to avoid a virtual function call, if you are worried about the cost, don't be - it is insignificant compared to the cost of I/O.

Not worried, apart from the nano-second saved I was looking for a challenge :)

> If you could give a description of how utp works, and how you have integrated it (for example, that there is only one "userdata" for the whole UTP socket instead of per-operation) that would be great

Not sure where to start. But let me try (also note that I'm not a libupt expert nor am I affiliated with the library): 

* libutp is nice in that it's only a state machine and the IO is done outside
* libutp has a `utp_context` per UDP socket (1-to-1).
* there can be many uTP sockets utilizing one UDP socket
* asio-utp also has a context (utp::context). utp::context _has_ utp_context
* utp::context also contains asio::ip::udp::socket and does IO on it
* note that writing to udp socket is not done using an `async_` function. It is done by setting the udp socket to non blocking mode and then writing to it. This is intentional because `would block` errors give libutp information about when the system queue is full
* the PIMPL pattern (having `socket_impl` pointer inside `socket`) is used mainly because when the `socket` is destroyed, we still need `libutp` to perform closing handshakes (send FIN packets and such).

That's about as much as I can squeeze from myself without you asking followup questions :), so feel free to do so. But it's half past midnight where I am so I may need to answer tomorrow.

**Comment by vinniefalco** [comment]
> Sounds good, but is there a convention I should know about?

Well... the `any_` prefix usually means the value form of type-erasure. Famous example, Boost.Any:
https://www.boost.org/doc/libs/1_61_0/doc/html/boost/any.html

**Comment by inetic** [comment]
Probably also worth adding that all the async responses from libutp are done through callbacks that are set using the  [`utp_set_callback`](https://github.com/inetic/libutp/blob/6c9ee29ed1d3fd06ba1856f01c8dd88eccaca2fa/utp.h#L152) function. In asio-utp this is done in [context.cpp](https://github.com/inetic/asio-utp/blob/master/src/context.cpp#L177).

**Comment by vinniefalco** [comment]
Globals like this are a problem:
https://github.com/inetic/asio-utp/blob/994f50f1d56d0f12ab97cc75f73f305ddd66fadf/src/context.cpp#L41

Globals associated with an `io_context` need to be installed using `asio::use_service`
https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/use_service/overload1.html

Your `context` is essentially a service, it just needs to be installed correctly.

**Comment by inetic** [comment]
> Globals like this are a problem:
> [asio-utp/src/context.cpp](https://github.com/inetic/asio-utp/blob/994f50f1d56d0f12ab97cc75f73f305ddd66fadf/src/context.cpp#L41)
> 
> Line 41 in [994f50f](/inetic/asio-utp/commit/994f50f1d56d0f12ab97cc75f73f305ddd66fadf)
> 
>  static std::map<endpoint_type, shared_ptr<context>> loops; 
> Globals associated with an `io_context` need to be installed using `asio::use_service`
> https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/use_service/overload1.html
> 
> Your `context` is essentially a service, it just needs to be installed correctly.

I created a new issue #4 for that

**Comment by inetic** [comment]
As a proof of concept, the modified coro client/server examples from Boost.Beast now work ('beast' branch):

https://github.com/inetic/asio-utp/tree/beast/example/http

It still doesn't solve the problems with associated executors, and non-service-globals, but that IMO should continue being dealt with in their own issue threads.

**Comment by vinniefalco** [comment]
This is very nice! I should probably change the examples to template functions like `do_session` on a **Stream** so then you would need to change even less.

I am now wondering, would it be possible to make a _Protocol_ out of UTP, the same way that Asio provides the `ip::tcp` protocol? Here are the requirements:
https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/reference/Protocol.html

If you do this, then I can change the beast examples to be templated on `Protocol`, that would be quite interesting!

**Comment by inetic** [comment]
I was [thinking about this as well in the benchmark](https://github.com/inetic/asio-utp/blob/beast/test/bench.cpp#L26). It uses a workaround, but the idea was similar in that I have one [templated code](https://github.com/inetic/asio-utp/blob/beast/test/bench.cpp#L252) to test upload/download speed with TCP and uTP sockets.

One of the main factors why `utp` isn't a class yet is a silly one: that I haven't figured out how to call the namespace that would replace the `utp` one :-) (I guess it's going to be either `asio_utp::utp` or `asioutp::utp`, but the consecutive `utp` strings grind my teeth a little :-) ).

There are also small issues with the API not being 100% the same. E.g. `utp::socket` doesn't have the `bind` function yet (it "binds" during construction), it doesn't have the `shutdown` function (I think libutp has added some shutdown mechanism to their sockets recently though), there isn't a `utp::acceptor`,...

But it'd indeed be a nice milestone to make the two as similar as possible.

**Comment by inetic** [comment]
> I am now wondering, would it be possible to make a Protocol out of UTP, the same way that Asio provides the ip::tcp protocol?

Created a new issue #5 for this.

**Comment by inetic** [comment]
Going to close this issue, `asio-utp` now does work with `beast` and the remaining issues will be dealt in their own threads.
